platform: x86

image: Visual Studio 2015

environment:
  global: # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the # /E:ON and /V:ON options are not enabled in the batch script intepreter # See: http://stackoverflow.com/a/13751649/163740
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
      - PYTHON: "C:\\Python34"
        PYTHON_VERSION: "3.4.3"
        PYTHON_ARCH: "32"
        DISTUTILS_USE_SDK: "1"
        PIP3: C:\\Python34\Scripts\pip

      - PYTHON: "C:\\Python34"
        PYTHON_VERSION: "3.4.3"
        PYTHON_ARCH: "64"
        DISTUTILS_USE_SDK: "1"
        PIP3: C:\\Python34\Scripts\pip

init:
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, verify which ones will be used
  - cmd: ECHO %PYTHON% %PYTHON3% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: "%PYTHON%\\python --version"
  - cmd: "%PYTHON%\\python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - cmd: ECHO %PYTHON3% %PYTHON3_VERSION% %PYTHON3_ARCH%
  - cmd: "%PYTHON3% --version"
  - cmd: "%PYTHON3% -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Prepare pip and pip3, PATH iterated left to right first hit wins
  - cmd: set PATH=%PYTHON%\scripts;%PYTHON3%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

install:
  - "ECHO Filesystem root:"
  - ps: "ls \"C:/\""

  - "ECHO Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%CMD_IN_ENV% %PIP3% install -r requirements.txt"

build_script:
  # Fix zope.interface package loading
  - "%CMD_IN_ENV% %PYTHON3% appveyor/zope_fix.py"

  # Build the compiled extension
  - "%CMD_IN_ENV% %PYTHON3% build_py2exe.py"

test_script:
  - "ECHO 'running non-existent tests...'"

after_test:
  # If tests are successful, create binary packages for the project.
  - "ECHO 'after test...'"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*
